#!/bin/sh

[ -f "/etc/clover/boardtype" ] || exit 1
CLV_BOARD_NAME="$(cat "/etc/clover/boardtype")"
MODULE="clvcon"
[ -f "/lib/modules/$(uname -r)/extra/$MODULE.ko" ] || MODULE="clovercon"

getboot2note(){
  local b2md5="$(hakchi getBackup2 | md5sum | awk '{print $1}')"
  grep -F "$b2md5" "/etc/firmwaredb" | cut -d\  -f4-
}

start(){
  local MODULE_PARAMS=""
  echo "$MODULE: starting driver"
  case "${CLV_BOARD_NAME}" in
    fp)
      # inverted c1/c2 detect lines
      MODULE_PARAMS="2,195,1,194"
    ;;
    dp-hvc)
      # no detect lines
      MODULE_PARAMS="1,-1,2,-1"
    ;;
    ep|dp-nes|dp-shvc|*)
      # regular setup w/ detect lines
      MODULE_PARAMS="1,195,2,194"
    ;;
  esac
  [ "$(getboot2note)" = "hardwired controllers" ] && MODULE_PARAMS="1,-1,2,-1"
  modprobe "$MODULE" "module_params=$MODULE_PARAMS"
}

stop(){
  echo "$MODULE: stopping driver"
  modprobe -r "$MODULE"
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    stop
    start
  ;;
  *)
    echo "Usage: $(basename "$0") {start|stop|status|restart}"
    exit 1
esac
