#!/bin/sh
NAME="remote-exec"
DAEMON="/bin/$NAME"
case "$1" in
  start)
    echo -n "Starting $NAME: "
    { start-stop-daemon -K -q -p "/run/$NAME.pid" -t 2>/dev/null || start-stop-daemon -S -q -b -N 10 -x "$DAEMON" -p "/run/$NAME.pid" -m
    } && echo "OK" || echo "Failed"
  ;;
  stop)
    echo -n "Stopping $NAME: "
    start-stop-daemon -K -q -p "/run/$NAME.pid" 2>/dev/null && echo "OK" || echo "Failed"
  ;;
  status)
    start-stop-daemon -K -q -p "/run/$NAME.pid" -t 2>/dev/null && echo "is running" && exit 0
    echo "not running" && exit 1
  ;;
  restart)
    "$0" stop
    "$0" start
  ;;
  *)
    echo "Usage: $(basename "$0") {start|stop|status|restart}"
    exit 1
  ;;
esac
