#!/bin/sh
source /etc/preinit
script_init

interfaces="/etc/network/interfaces"

start(){
  if [ "$(usbMode)" != "host" ]; then
    echo "usbMode: $(usbMode)"
    exit 1
  fi

  ifup -a
  for i in $(ls "$interfaces.d"); do
    ifaceDown "$i" && ifup "$i" -i "$interfaces.d/$i" &
  done
}

stop(){
  for i in $(ls -r "$interfaces.d"); do
    ifdown "$i" -i "$interfaces.d/$i" 2>/dev/null
    ip link set "$i" down 2>/dev/null
  done
  ifdown -a
  ip link set lo down
}

restart(){
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  udev)
    ifaceUp "lo" || exit 0
    [ "$(usbMode)" = "host" ] || exit 1
    local self="$(readlink -f "$0")"
    echo "\"$self\" udev-detached" >> "/var/exec.flag"
  ;;
  udev-detached)
    [ "$(usbMode)" = "host" ] || exit 1
    sleep 2
    restart
  ;;
  *)
    echo "Usage: $(basename "$0") {start|stop|status|restart}"
    exit 1
  ;;
esac
