#!/bin/sh
/squashtools/sfdisk /dev/mmcblk0 <<EOT
32M,96M,06
128M,,L
EOT

yes | mke2fs -t ext4 -L data -b 4K -E stripe-width=32 -O ^huge_file,^metadata_csum /dev/mmcblk0p2
mkdir /data
mount /dev/mmcblk0p2 /data
rsync -ac /squashtools/fsroot/ /data/
mkdir -p /data/hakchi/transfer/
rsync -ac /squashtools/extra-hmods/ /data/hakchi/transfer/
sync
umount /data
rmdir /data
umount /squashtools
rmdir /squashtools
