#!/bin/sh

mod_uninstall(){
  echo "uninstalling $modname..."
  rm -rf "$installpath"
  echo "done."
  shutdown
}

mod_repair(){
  local packName=""
  while read -r packName; do
    pack_uninstall "$packName"
  done < "/etc/hmodblacklist"

  local bin="$temppath/bin"
  rm -rf "$bin"
  mkdir -p "$bin"
  copy "$mountpoint/bin/" "$bin/"
  copy "/bin/" "$bin/"
  copy "$modpath/rootfs/bin/" "$bin/"
  [ -f "/sbin/cryptsetup" ] && copy "/sbin/cryptsetup" "$bin/cryptsetup"
  copy "$bin/" "$modpath/rootfs/bin/"
  rm -rf "$bin"

  [ -f "/key-file" ] && copy "/key-file" "$modpath/rootfs/etc/key-file"
  chown -R 0:0 "$modpath/"
  cd "$modpath/rootfs/bin" && chmod 755 *
  cd "$modpath/rootfs/etc/init.d" && chmod 755 *
  rm -f "$modpath/rootfs/etc/preinit.d/p0000_config"
  copy "$modpath/rootfs/" "$rootfs/"

  mod_repair_etc full
  find "$preinit.d/" -type f -name "*.tmp" -delete
  cd /
}

mod_install(){
  echo "installing $modname..."
  rm -rf "$rootfs"
  mod_repair
}
