#!/bin/sh

init(){
  echo
  export modname="hakchi"
  export modpath="/$modname"
  export mountpoint="/newroot"
  export temppath="/tmp"

  /bin/busybox --install -s /bin/
  mkdir -p "$temppath"
  for dir in etc lib usr; do
    [ -e "/$1" ] || ln -s "$mountpoint/$1" "/$1"
  done
  export PATH="/sbin:$modpath/rootfs/bin:/bin:$mountpoint/sbin:/usr/sbin:$mountpoint/bin:/usr/bin"

  source "$modpath/config"
  source "$modpath/script/base"

  if [ -d "$modpath/transfer" ]; then
    cf_usb='n'
    source "$modpath/script/transfer"
  else
    mount_base
  fi

  if [ -f "$preinit" ]; then
    PATH="$rootfs/sbin:$rootfs/usr/sbin:$rootfs/bin:$rootfs/usr/bin:$PATH"
    "$rootfs/bin/busybox" sh -c "source "$preinit.d/b0000_defines" && source "$preinit" && preinit"
  else
    umount_base
  fi
}

init
echo
