#!/bin/sh

cfg_boot_stock='n'
[ -z "$cfg_disable_armet" ] && cfg_disable_armet='y'
[ -z "$cfg_firmware" ] && cfg_firmware='auto'
cfg_usb_host='y'
[ -z "$cfg_usb_rw" ] && cfg_usb_rw='n'
[ -z "$cfg_wood" ] && cfg_wood='n'
