#!/bin/sh

if [ -f "/sys/devices/sunxi_usb/usb_role" ]; then
  if [ "$cfg_usb_host" = "n" ] || [ "$cf_memboot" = "y" ]; then
    [ "$cf_undershell" = "y" ] || switchToUsbDevice
  else
    switchToUsbHost
    # the usb driver needs some time to initialize
    sleep 1
    if [ -z "$(lsusb | grep -v "1d6b:")" ]; then
      switchToUsbDevice
    fi
  fi
fi

echo "usbMode: $(usbMode)"
checkExtStorage
