#!/bin/sh

if [ "$cf_undershell" != "y" ] && [ -f "/sys/devices/sunxi_usb/usb_role" ]; then
  if [ "$cfg_usb_host" = "n" ] || [ "$cf_memboot" = "y" ]; then
    switchToUsbDevice
  else
    switchToUsbOTG
  fi
fi

echo "usbMode: $(usbMode)"
checkExtStorage
